### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by mrmattwilkins** [PeRDy/django-numpy#3]
I think you may need to update your setup.py?
```
root@hostname:~# pip3 install django-numpy
Collecting django-numpy
  Downloading https://files.pythonhosted.org/packages/35/b0/1f0be2e9c4df3b0736b09067dd041eb4475a6199b583428b241eb8576d7d/django-numpy-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-snfzenz_/django-numpy/setup.py", line 6, in <module>
        from pip.download import PipSession
    ModuleNotFoundError: No module named 'pip.download'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-snfzenz_/django-numpy/
```

**Comment by JimInCO** [comment]
I also had this issue. It has been resolved by PR #2. The updated code however has not yet been released to the pypi server.

**Comment by gomeslucasm** [comment]
I have the same error, how can I fix it?

**Comment by lfaucheux** [comment]
The easiest way @gomeslucasm : install [git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) and do `pip install git+https://github.com/perdy/django-numpy.git` instead of `pip install django-numpy `.
